### ISSUE TITLE
Error with nextjs

### ISSUE THREAD

**Issue by rickgbw** [rommguy/react-custom-scroll#50]
Hi!
Using this component on a SSR project (nextjs), I got this error:

```
{ ReferenceError: window is not defined
     at Object.<anonymous> (/Users/user/Documents/workspace/project/app/node_modules/react-custom-scroll/dist/reactCustomScroll.js:1:538)
     at Module._compile (module.js:652:30)
     at Object.Module._extensions..js (module.js:663:10)
     at Module.load (module.js:565:32)
     at tryModuleLoad (module.js:505:12)
     at Function.Module._load (module.js:497:3)
     at Module.require (module.js:596:17)
     at require (internal/module.js:11:18)
     at Object.<anonymous> (/Users/user/Documents/workspace/project/app/node_modules/react-custom-scroll/index.js:2:22)
     at Module._compile (module.js:652:30)
     at Object.Module._extensions..js (module.js:663:10)
     at Module.load (module.js:565:32)
     at tryModuleLoad (module.js:505:12)
     at Function.Module._load (module.js:497:3)
     at Module.require (module.js:596:17)
     at require (internal/module.js:11:18) sourceMapsApplied: true }
```

Maybe should check if is on server side (`typeof window !== 'undefined'`) before using `window`...

**Comment by rommguy** [comment]
Hi @rickgbw!
Glad you're using this component.
I'm not too familiar with server side rendering issues - what about getBoundingClientRect ? 
Should I avoid that one too ?
How do you simulate DOM on server side ?

**Comment by rodgobbi** [comment]
Hi @rommguy,
I stumbled on the same problem when trying to upgrade from version 2, meaning that version 2 works perfectly with next but after that it throws this error.
Accessing the web API's after the component is mounted is OK for SSR: [nextjs FAQ](https://github.com/zeit/next.js/wiki/FAQ).
From what I checked of the source code, the `getBoundingClientRect` is only used when reacting to a click event, which is fine, it's used like that in version 2.

**Comment by rommguy** [comment]
@rodgobbi I'd love to fix this but the only usage of window is in the calculateNewScrollHandleTop method that is called when clicking on the scroll area. There is no window usage during rendering. 
Can you please try and provide some more information on the error ?

**Comment by rodgobbi** [comment]
@rommguy, thanks for the attention!
So, I checked it too, the source code looks perfect, the only thing that seems to be causing trouble is the `dist` code which uses `window`: (I formatted the code for better readability)  
![code](https://user-images.githubusercontent.com/3410227/46477255-acb52100-c7c0-11e8-94bd-f7494f428330.png)
So when `window` is passed in as argument, it throws the exception.
Because of that I wonder that it's possibly the build process that is generating that code with `window` and causing the bug, but I may be talking nonsense, I don't have much experience on maintaining open source libs :(. That's just a superficial thought from me, I'd need to investigate much more.
I hope this info helps, if you need more, I can gladly help. :)

**Comment by hypercodex** [comment]
Hi trying this package out and hitting the same issue. NextJs 7. I'd say the above diagnosis per the SSR considerations appears to be correct. Now how to fix..?

**Comment by hypercodex** [comment]
Hi quick update: We were able to get around the window problems in NextJs SSR by using a next/dynamic import. Like so:
```
const CustomScroll = dynamic(
  import('react-custom-scroll'),
  { ssr: false }
)
```

Hope that helps. Regards
